### ISSUE TITLE
Tela de Cadastro

### ISSUE THREAD

**Issue by Denniel-sudo** [UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_Mobile#1]
## Descrição da Issue

Criar a tela de cadastro de usuário

## Tasks:
- [ ] Criar os componentes
- [ ] Criar as validações dos campos
- [ ] Enviar requisição pro backend
- [ ] Configurar navigation entre telas

## Critérios de Aceitação:
- [ ] Tela criada e testada
